### ISSUE TITLE
[Bug]license strike due to not uploading 1.0.8 to cf

### ISSUE THREAD

**Issue by VaporeonScripts** [Stardust-Labs-MC/Structory-Towers#5]
### What Minecraft version(s) does this apply to?

1.21 - 1.21.1

### Project version

1.0.8

### Mod or datapack version?

Neoforge/Forge Mod

### Describe the bug

i get license strike from ur mod due to u not putting the new update in cf, may u do that pls?

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/3787778d-a501-451b-88b1-dd78b7467a0c)

**Comment by catter1** [comment]
Will do. When I initially uploaded 1.0.8 to Modrinth, for some reason Curseforge was being weird and refused to let me upload. I since forgot to try again

**Comment by catter1** [comment]
Uploaded - once Curseforge approves the file, [this](https://www.curseforge.com/minecraft/mc-mods/structory-towers/files/5800614) should be the direct link to it.

**Comment by VaporeonScripts** [comment]
alright,ty!

**Comment by VaporeonScripts** [comment]
what can i do about this?
![image](https://github.com/user-attachments/assets/922600c6-6a53-438e-aeb1-dc33a3975f14)

**Comment by catter1** [comment]
I do not know how CurseForge's modpack moderation works. At least to me, it simply means "don't add the files to your modpack - just reference the mods in `manifest.json`." You should instead ask the Curseforge support team like they recommend if you have further questions on that.
